### PR TITLE
Attribute the XKCD comic.

### LINKED ISSUE #48: xkcd copyright/license violation (lack of attribution) in README
The file: https://github.com/ossf/wg-securing-critical-projects/blob/main/README.md

Has an image obviously from https://xkcd.com/2347/ but seems to lack any attribution.  The content is licensed: https://creativecommons.org/licenses/by-nc/2.5/

### PR DESCRIPTION
**Pull request by calebbrown**
Fixes #48

### CODE REVIEW

**Review by jchestershopify — APPROVED** [review]
LGTM.

**Comment by calebbrown** [comment]
Thanks @jchestershopify!

Are you able to merge? I don't have write access

**Comment by jchestershopify** [comment]
No, I'm afraid not. There doesn't seem to be a defined team for this repo. @jorydotcom or @david-a-wheeler, are you able to merge?

**Comment by david-a-wheeler** [comment]
I just merged it!

**Comment by calebbrown** [comment]
Thank you!

**Pull request merged**
